### ISSUE TITLE
Pending go annotations

### ISSUE THREAD

**Issue by manulera** [manulera/discussions_curation#15]
* [x] Spindle elongation during anaphase B should probably be a term.
  * [x] Annotate cut7 and klp9 here.

**Comment by ValWood** [comment]
That was the purpose of the phase III term

GO:0061805   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0061805/complete)
mitotic spindle elongation (spindle phase three)
Biological Process

Definition 
The cell cycle process in which the distance is lengthened between poles of the mitotic spindle during mitotic anaphase B. PMID:21920317

but maybe   these terms would be better labelled as "during anaphase B" etc.

**Comment by manulera** [comment]
* [ ] Create and discuss ticket in GO for spindle pole terms

**Comment by manulera** [comment]
> That was the purpose of the phase III term

You are absolutely right, sorry. This was an item in a list that I wrote before looking into that and I just copy pasted it to take it out of the todo list of another ticket. I will do that.

**Comment by ValWood** [comment]
Remember for "spindle pole" the ontology organization looks a bit strange, because "spindle poles" are not always part_of spindles (just  in case it is relevant)
