### ISSUE TITLE
Microtubule dynamics - phenotype ontologies

### ISSUE THREAD

**Issue by manulera** [manulera/discussions_curation#4]
## Introduction

* Microtubules are filaments composed of $\alpha$ and $\beta$ tubulin subunits.
* They can grow or shrink only at their tips.
* They are polar, with two different ends, labelled plus end and minus end.
* In *pombe*, minus ends are not dynamic, since they are capped by $\gamma$-tubulin, but plus ends undergo the process called __dynamic instability__ (see cartoon below):
  * They alternate between two phases of persistent growth (microtubule polymerisation) and persistent shrinkage (microtubule depolymerisation).
  * Transition from growth to shrinkage is called a "catastrophe".
  * Transition from shrinkage to growth is called "rescue".

![](https://www.researchgate.net/profile/Marija-Zanic/publication/236084130/figure/fig3/AS:271183509716993@1441666595305/Microtubule-dynamic-instability-Microtubules-are-13-protofilament-cylindrical-polymers.png)

## Current ontology

There are currently the following terms referring to microtubule dynamics, with their children:

### FYPO:0000901 abnormal microtubule polymerization or depolymerization during vegetative growth

```mermaid
graph LR;
      FYPO:0000902[FYPO:0000902<br>abnormal microtubule<br> depolymerization du<br>ring vegetative grow<br>th]-->FYPO:0007706[FYPO:0007706<br>decreased microtubul<br>e depolymerization a<br>t cell side];
      FYPO:0000902[FYPO:0000902<br>abnormal microtubule<br> depolymerization du<br>ring vegetative grow<br>th]-->FYPO:0004650[FYPO:0004650<br>decreased mitotic sp<br>indle microtubule de<br>polymerization];
      FYPO:0004650[FYPO:0004650<br>decreased mitotic sp<br>indle microtubule de<br>polymerization]-->FYPO:0005423[FYPO:0005423<br>decreased mitotic sp<br>indle microtubule de<br>polymerization durin<br>g anaphase A];
      FYPO:0000902[FYPO:0000902<br>abnormal microtubule<br> depolymerization du<br>ring vegetative grow<br>th]-->FYPO:0004616[FYPO:0004616<br>abolished cytoplasmi<br>c microtubule depoly<br>merization at plus e<br>nd at cell tip];
      FYPO:0000902[FYPO:0000902<br>abnormal microtubule<br> depolymerization du<br>ring vegetative grow<br>th]-->FYPO:0003194[FYPO:0003194<br>increased rate of mi<br>crotubule depolymeri<br>zation during vegeta<br>tive growth];
      FYPO:0004614[FYPO:0004614<br>abnormal microtubule<br> polymerization]-->FYPO:0005681[FYPO:0005681<br>decreased microtubul<br>e polymerization];
      FYPO:0000901[FYPO:0000901<br>abnormal microtubule<br> polymerization or d<br>epolymerization duri<br>ng vegetative growth]-->FYPO:0000902[FYPO:0000902<br>abnormal microtubule<br> depolymerization du<br>ring vegetative grow<br>th];
      FYPO:0000902[FYPO:0000902<br>abnormal microtubule<br> depolymerization du<br>ring vegetative grow<br>th]-->FYPO:0007182[FYPO:0007182<br>decreased cytoplasmi<br>c microtubule depoly<br>merization at plus e<br>nd at cell tip];
      FYPO:0000902[FYPO:0000902<br>abnormal microtubule<br> depolymerization du<br>ring vegetative grow<br>th]-->FYPO:0005682[FYPO:0005682<br>decreased microtubul<br>e depolymerization d<br>uring vegetative gro<br>wth];
      FYPO:0000902[FYPO:0000902<br>abnormal microtubule<br> depolymerization du<br>ring vegetative grow<br>th]-->FYPO:0003190[FYPO:0003190<br>decreased rate of cy<br>toplasmic microtubul<br>e depolymerization];
      FYPO:0003194[FYPO:0003194<br>increased rate of mi<br>crotubule depolymeri<br>zation during vegeta<br>tive growth]-->FYPO:0004976[FYPO:0004976<br>increased rate of mi<br>crotubule depolymeri<br>zation ahead of movi<br>ng spindle pole body];
      FYPO:0003194[FYPO:0003194<br>increased rate of mi<br>crotubule depolymeri<br>zation during vegeta<br>tive growth]-->FYPO:0004617[FYPO:0004617<br>increased rate of mi<br>crotubule depolymeri<br>zation at minus end];
      FYPO:0004614[FYPO:0004614<br>abnormal microtubule<br> polymerization]-->FYPO:0005703[FYPO:0005703<br>decreased rate of mi<br>crotubule polymeriza<br>tion];
      FYPO:0004614[FYPO:0004614<br>abnormal microtubule<br> polymerization]-->FYPO:0004615[FYPO:0004615<br>increased rate of in<br>terphase microtubule<br> polymerization];
      FYPO:0000902[FYPO:0000902<br>abnormal microtubule<br> depolymerization du<br>ring vegetative grow<br>th]-->FYPO:0000903[FYPO:0000903<br>decreased rate of mi<br>crotubule depolymeri<br>zation during vegeta<br>tive growth];
      FYPO:0004614[FYPO:0004614<br>abnormal microtubule<br> polymerization]-->FYPO:0006180[FYPO:0006180<br>increased microtubul<br>e polymerization];
      FYPO:0000903[FYPO:0000903<br>decreased rate of mi<br>crotubule depolymeri<br>zation during vegeta<br>tive growth]-->FYPO:0004721[FYPO:0004721<br>decreased rate of mi<br>crotubule depolymeri<br>zation at minus end];
      FYPO:0004650[FYPO:0004650<br>decreased mitotic sp<br>indle microtubule de<br>polymerization]-->FYPO:0005363[FYPO:0005363<br>decreased kinetochor<br>e microtubule depoly<br>merization during mi<br>totic metaphase chro<br>mosome recapture];
      FYPO:0004614[FYPO:0004614<br>abnormal microtubule<br> polymerization]-->FYPO:0005463[FYPO:0005463<br>decreased spatial ex<br>tent of interphase m<br>icrotubule polymeriz<br>ation];
      FYPO:0000901[FYPO:0000901<br>abnormal microtubule<br> polymerization or d<br>epolymerization duri<br>ng vegetative growth]-->FYPO:0004614[FYPO:0004614<br>abnormal microtubule<br> polymerization];
      FYPO:0000903[FYPO:0000903<br>decreased rate of mi<br>crotubule depolymeri<br>zation during vegeta<br>tive growth]-->FYPO:0004975[FYPO:0004975<br>decreased rate of mi<br>crotubule depolymeri<br>zation behind moving<br> spindle pole body];
      FYPO:0000902[FYPO:0000902<br>abnormal microtubule<br> depolymerization du<br>ring vegetative grow<br>th]-->FYPO:0006105[FYPO:0006105<br>increased microtubul<br>e depolymerization a<br>t cell side];
      FYPO:0004614[FYPO:0004614<br>abnormal microtubule<br> polymerization]-->FYPO:0006067[FYPO:0006067<br>abolished microtubul<br>e polymerization];
```

### FYPO:0007111 abnormal microtubule depolymerization

```mermaid
graph LR;
      FYPO:0007111[FYPO:0007111<br>abnormal microtubule<br> depolymerization]-->FYPO:0007112[FYPO:0007112<br>decreased rate of mi<br>crotubule depolymeri<br>zation involved in m<br>eiotic centromere cl<br>ustering during meio<br>tic prophase I];
```

### Others

* FYPO:0003193 - Normal rate of MT depol
* FYPO:0003225 - Normal rate of MT pol

These two should be probably add "during vegetative growth", since they are children of "FYPO:0000899", "normal microtubule cytoskeleton organization during vegetative growth "

Then there is "abnormal kinetochore microtubule polymerization during mitotic metaphase chromosome recapture" FYPO:0006040, which should also be linked to mt dynamics, and is only linked to FYPO:0005362 (abnormal mitotic metaphase chromosome recapture)

## Proposed changes

1. Rename FYPO:0000901 to abnormal microtubule dynamics during vegetative growth. Then make four children:

   * Abnormal microtubule depolymerisation rate:
     * This can already become the parent of the terms that were specific and mentioned depolymerisation <u>rate</u>, such as FYPO:0003194.
     * I can revisit the annotations of the others, and re-assign them.
   * Abnormal microtubule polymerisation rate:
     * Same
     * Terms from my paper specific to anaphase B should come as children
   * Abnormal microtubule growth event duration:
     * Since what is measured to calculate catastrophe rates is the duration of the growth events, the phenotype should be that.
     * In addition, the term "rescue rate" is problematic, since the use of "rate" kind of implies that the rate is constant, while in reality the catastrophe rate increases with microtubule age in the absence of other proteins, and even more so in the cell with the action of molecules such as kinesins-8 (klp5/klp6).
     * Terms from my paper specific to anaphase B should come as children (klp5/klp6 phenotype)
   * Abnormal microtubule rescue:
     * A bit similar to the catastrophe, rescue cannot really be measured directly, but it's distribution (ase1D perturbs distribution of rescue) or total absence can be (cls1/peg1 thermosensitive mutant prevents rescue during anaphase B). peg1 overexpression causes superstable microtubules due to excess rescue, but it's hard to provide "direct evidence" or a measurement (Bratman and Chang 2007).

   The annotations from terms that are not specific and just say "decrease depolymerisation" should be revisited and assigned to the right term (depending on whether they affected shrinkage speed or growth event duration). Same applies to others like FYPO:0005463 (decreased spatial extent of interphase microtubule polymerization), they probably can be pinpointed to increased/decreased growth/shrinkage speed or duration. I can do this in the future.

2. Rename FYPO:0007111 to depol. rate, since the child is specific to that
3. Adding "during vegetative growth" to FYPO:0003193 and FYPO:0003225, since they are children of "FYPO:0000899", "normal microtubule cytoskeleton organization during vegetative growth "
4. Linking FYPO:0006040 to the child of FYPO:0000901 with decrease microtubule depolymerisation rate.
5. Edit the synonyms as well.

### Requested terms - MT dynamics

* For the "abnormal" microtubule polym. and depolym. rates, I don't know if the default is to already add the increased/decreased children. I guess there will be annotations for both cases, and they are typically regulated by different proteins, so probably there will not be terms without annotations.

|Term name/ id|Request|New definition|New name|Child of (if added)|
|-------|-------|-------|-------|-------|
|FYPO:0000901|Change name and definition|A cellular process phenotype observed in the vegetative growth phase of the life cycle in which microtubule dynamics are abnormal.|abnormal microtubule dynamics during vegetative growth|
|Abnormal microtubule depolymerisation rate|Addition|A cellular process phenotype observed in the vegetative growth phase of the life cycle in which the rate, or speed, of microtubule polymerization, i.e. the addition of tubulin dimers to a microtubule, is abnormal (matching FYPO:0003225)||FYPO:0000901|
|Abnormal microtubule polymerisation rate|Addition|A cellular process phenotype observed in the vegetative growth phase of the life cycle in which the rate, or speed, of microtubule depolymerization, i.e. the removal of tubulin dimers to a microtubule, is abnormal (matching FYPO:0003193)||FYPO:0000901|
|Abnormal microtubule growth event duration|Addition|A cellular process phenotype observed in the vegetative growth phase of the life cycle in which the duration of microtubule growth events is abnormal||FYPO:0000901|
|Abnormal microtubule rescue|Addition|A cellular process phenotype observed in the vegetative growth phase of the life cycle in which microtubule rescue (the transition from shrinkage to growth) is abnormal. The frequency of rescues as well as the organisation can be affected.||FYPO:0000901|
|FYPO:0007111|Change name and definition|A cellular process phenotype in which the rate, or speed, of microtubule polymerization, i.e. the addition of tubulin dimers to a microtubule, is abnormal (matching FYPO:0003225)|Abnormal microtubule depolymerization rate|

### Change in synonyms

These are either for FYPO:0000901, or for the terms that were already specific and mentioned growth/shrinkage **rate**.

|Term name/ id|Existing synonym|Proposed change|Reason|
|-------|-------|-------|-------|
|FYPO:0000901|[all](https://bioportal.bioontology.org/ontologies/FYPO/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFYPO_0000901&jump_to_nav=true)|None|I guess they can be left like this, since they mention both growth and shrinkage|
|FYPO:0003193|normal rate of microtubule catastrophe|remove|Catastrophe, not depolymerisation.|
|FYPO:0003194|The ones that mention stability and catrastrophe|remove|Catastrophe, not depolymerisation.|
|FYPO:0003190|The ones that mention stability and catrastrophe|remove|Catastrophe, not depolymerisation.|
|FYPO:0007111|catastrophe|remove|Catastrophe, not depolymerisation.

**Comment by ValWood** [comment]
Yes this all makes sense. You can transfer the requests to the FYPO tracker. It seems straightforward, but I can ask if I get stuck.
v
